FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.17  as builder

WORKDIR /src

# Build
ARG TARGETOS TARGETARCH
RUN --mount=target=. \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -ldflags="-s -w" -o /out/onionbalance-local-manager ./agents/onionbalance/main.go

FROM docker.io/library/alpine:3.17.3

ARG VERSION=0.2.2

RUN apk add --no-cache --update \
        git=2.38.4-r1 \
        py3-cryptography=38.0.3-r1 \
        py3-pip=22.3.1-r1 \
        py3-pycryptodomex=3.15.0-r0 \
        py3-setproctitle=1.3.1-r0 \
        py3-wheel=0.38.4-r0 \
        python3=3.10.11-r0 \
    && python3 -m pip install --no-cache-dir git+https://gitlab.torproject.org/tpo/core/onionbalance.git@${VERSION}

COPY --from=builder /out/onionbalance-local-manager /

ENTRYPOINT ["/onionbalance-local-manager"]
