---
{{- if .Values.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tor-controller.fullname" . }}-manager-crd-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tor-controller.fullname" . }}-manager-crd-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tor-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "tor-controller.roleBindingKind" . }}
metadata:
  name: {{ include "tor-controller.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "tor-controller.roleKind" . }}
  name: {{ include "tor-controller.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tor-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "tor-controller.roleBindingKind" . }}
metadata:
  name: {{ include "tor-controller.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "tor-controller.roleKind" . }}
  name: {{ include "tor-controller.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tor-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
