# permissions for end users to view tors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tor-viewer-role
rules:
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - tors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - tors/status
  verbs:
  - get
