apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionBalancedService
metadata:
  name: example-onionbalanced-service
spec:
  backends: 2
  serviceMonitor: true
  template:
    spec:
      version: 3
      serviceMonitor: true
      rules:
        - port:
            number: 80
          backend:
            service:
              name: http-app
              port:
                number: 8080
