apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: example-onion-service
spec:
  version: 3
  rules:
    - port:
        number: 80
      backend:
        service:
          name: http-app
          port:
            number: 8080
  template:
    metadata:
      annotations:
        some-special-anotation: my-value
    resources:
      limits:
        cpu: 500m
        memory: 128Mi