# Default values for tor-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- If enabled, permissions are restricted to the target Namespace
namespaced: false

# -- Daemonset replica count
replicaCount: 1

# -- tor-controller image, it watches onionservices objects
image:
  repository: quay.io/bugfest/tor-controller
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

daemon:
  # -- tor-daemon image, it runs Tor client
  image:
    repository: quay.io/bugfest/tor-daemon
    pullPolicy: Always
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""

manager:
  # -- tor-daemon-manager image, it runs Tor client with manager
  image:
    repository: quay.io/bugfest/tor-daemon-manager
    pullPolicy: Always
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""

onionbalance:
  # -- tor-onionbalance-manager image, it runs Tor client
  image:
    repository: quay.io/bugfest/tor-onionbalance-manager
    pullPolicy: Always
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 250m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
